### ISSUE TITLE
phpcs not working (previously working :S)

### ISSUE THREAD

**Issue by slifin** [SublimeLinter/SublimeLinter-phpcs#44]
Does this make any sense?

```
plugins loaded
Exception in thread Thread-4:
Traceback (most recent call last):
  File "./python3.3/json/decoder.py", line 367, in raw_decode
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./python3.3/threading.py", line 901, in _bootstrap_inner
  File "./python3.3/threading.py", line 1142, in run
  File "/Users/adriansmith/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package/sublime_linter.py", line 269, in lint
    linters = get_linters_for_view(view)
  File "/Users/adriansmith/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package/sublime_linter.py", line 370, in get_linters_for_view
    wanted_linters.append(linter_class(view, settings))
  File "/Users/adriansmith/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package/lint/base_linter/composer_linter.py", line 32, in __init__
    self.read_manifest(os.path.getmtime(self.manifest_path))
  File "/Users/adriansmith/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package/lint/base_linter/composer_linter.py", line 159, in read_manifest
    self.cached_manifest = json.load(codecs.open(self.manifest_path, 'r', 'utf-8'))
  File "./python3.3/json/__init__.py", line 271, in load
  File "./python3.3/json/__init__.py", line 316, in loads
  File "./python3.3/json/decoder.py", line 351, in decode
  File "./python3.3/json/decoder.py", line 369, in raw_decode
ValueError: No JSON object could be decoded
```

**Comment by kaste** [comment]
Well that's an ugly error, but the root issue here is that the plugin found a `composer.json` but cannot read its contents.
